import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // Import Link

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Data Explorer", // Updated title
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Header */}
        <header className="bg-white shadow-md p-4">
          <nav className="max-w-7xl mx-auto flex justify-between items-center">
            <Link href="/" className="text-2xl font-bold text-green-700">
              Product Explorer
            </Link>
            <Link href="/about" className="text-gray-600 hover:text-green-700">
              About
            </Link>
          </nav>
        </header>

        {/* This is where your page content will go */}
        <div className="flex-grow">{children}</div>
        
        {/* Footer */}
        <footer className="bg-gray-800 text-white text-center p-4 mt-auto">
          <p>Built by [Your Name Here]</p> {/* <-- ADD YOUR NAME! */}
        </footer>
      </body>
    </html>
  );
}